#!/bin/bash

# this script is autogenerated by 'ant startscripts'
# it starts a LAS2peer node providing the service 'MyCalendar' of this project
# pls execute it from the root folder of your deployment, e. g. ./bin/start_network.sh

java -cp "lib/*" i5.las2peer.tools.L2pNodeLauncher -p 9011 "uploadStartupDirectory" "startService('i5.las2peer.services.contactService.ContactService@1.0')" "startService('i5.las2peer.services.threadedCommentService.ThreadedCommentService@0.1')"  "startService('i5.las2peer.services.calendar.MyCalendar@0.1')" startWebConnector interactive

